---
title: "PS4442 Final Project RSM"
author: "Ethan Engel"
date: "5/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
library(tidyverse)
library(rsm)
```


```{r cars}
ghi<-read.csv("ghi_rsm.csv")
head(ghi)
count(ghi)
```
#https://cran.r-project.org/web/packages/rsm/vignettes/rsm.pdf

```{r pressure, echo=FALSE}
boxplot(ghi$GHI_score,xlab="GHI Scores",horizontal = TRUE)
qqnorm(ghi$GHI_score, pch = 1, frame = FALSE)
qqline(ghi$GHI_score, col = "steelblue", lwd = 2)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
library(rsm)

rsm_1st_order <- rsm(GHI_score ~ FO(FSI_score, GDP_capita, curr_temp_change), data = ghi)
#FO=1st order/linear

rsm_1order_TWI<- rsm(GHI_score ~ FO(FSI_score, GDP_capita, curr_temp_change)+TWI(FSI_score, GDP_capita, curr_temp_change), data = ghi)
#TWI - 2 way interactions

rsm_2order_noTWI <- rsm(GHI_score ~ FO(FSI_score, GDP_capita, curr_temp_change) + PQ(FSI_score, GDP_capita, curr_temp_change), data = ghi)
#PQ - Pure Quadratic

rsm_2order<-rsm(GHI_score ~ SO(FSI_score, GDP_capita, curr_temp_change),data=ghi)
#SO- 2nd order: 1st order & 2-way interactions & pure quadratic terms               
```
```{r}
anova(rsm_2order_noTWI, rsm_2order)
AIC(rsm_2order_noTWI, rsm_2order)
```
```{r}
AIC(rsm_1st_order,rsm_2nd_order_noTWI,rsm_2order)
```
```{r}
par(mfrow=c(1,2))
contour(rsm_1st_order, ~ FSI_score + GDP_capita, image = TRUE, main="first-order model")

persp(rsm_1st_order, FSI_score ~ GDP_capita, zlab = "GHI_score", main="first-order model")
par(mfrow=c(1,2))
contour(rsm_2nd_order_noTWI, ~ FSI_score + GDP_capita, image = TRUE, main="2nd-order model w/o interactions")
persp(rsm_2nd_order_noTWI, FSI_score ~ GDP_capita, zlab = "GHI_score", main="2nd-order model w/o interactions")
```
```{r}


```

